# Generated by Django 5.2.4 on 2025-07-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='default/news.jpg', null=True, upload_to='news/'),
        ),
    ]
